FROM debian:bookworm-slim

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    python3-venv \
    krb5-user \
    dnsutils \
    curl \
    hashcat \
    && rm -rf /var/lib/apt/lists/*

# Install impacket in venv
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install --no-cache-dir impacket==0.12.0

WORKDIR /lab
